TOPICS = ["all", "grid", "tree", "graph", "array", "string", "dp"]
DIFFICULTIES = ["all", "easy", "medium", "hard"]

PROBLEMS = [
    {"id": "count_islands",      "title": "Count Islands",                  "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "number_of_islands",  "title": "Number of Islands II",           "topic": "grid",   "difficulty": "hard",   "renderer": "grid",  "available": False},
    {"id": "bt_inorder",         "title": "Binary Tree Inorder Traversal",  "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_preorder",        "title": "Binary Tree Preorder Traversal", "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_postorder",       "title": "Binary Tree Postorder Traversal", "topic": "tree",  "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_max_depth",       "title": "Maximum Depth of Binary Tree",   "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_path_sum",        "title": "Binary Tree Path Sum",           "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_level_order",     "title": "Binary Tree Level Order BFS",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "balanced_bt",        "title": "Balanced Binary Tree",           "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "diameter_bt",        "title": "Diameter of Binary Tree",        "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "flatten_tree",       "title": "Flatten Binary Tree to List",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "invert_tree",        "title": "Invert Binary Tree",             "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "kth_smallest_bst",   "title": "Kth Smallest Element in BST",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "lca_bst",            "title": "Lowest Common Ancestor of BST",  "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "lca_bt",             "title": "Lowest Common Ancestor of BT",   "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "max_path_sum",       "title": "Binary Tree Max Path Sum",       "topic": "tree",   "difficulty": "hard",   "renderer": "tree",  "available": True},
    {"id": "path_sum_ii",        "title": "Binary Tree Path Sum II",        "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "right_side_view",    "title": "Binary Tree Right Side View",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "sum_numbers",        "title": "Sum Root to Leaf Numbers",       "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "symmetric_tree",     "title": "Symmetric Tree",                 "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "validate_bst",       "title": "Validate Binary Search Tree",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "zigzag_level_order", "title": "BT Zigzag Level Order BFS",      "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "two_sum",            "title": "Two Sum",                        "topic": "array",  "difficulty": "easy",   "renderer": "array", "available": True},
    {"id": "merge_intervals",    "title": "Merge Intervals",                "topic": "array",  "difficulty": "medium", "renderer": "array", "available": True},
    {"id": "valid_parens",       "title": "Valid Parentheses",              "topic": "string", "difficulty": "easy",   "renderer": "array", "available": True},
    {"id": "dijkstra",           "title": "Dijkstra Shortest Path",         "topic": "graph",  "difficulty": "medium", "renderer": "graph", "available": True},
    {"id": "bfs_graph",          "title": "Graph BFS",                      "topic": "graph",  "difficulty": "easy",   "renderer": "graph", "available": True},
    {"id": "lcs",                "title": "Longest Common Subsequence",     "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
]

# Map renderer name → module path for dynamic loading
RENDERER_MAP = {
    "grid":  "neonodes.renderers.grid.GridRenderer",
    "tree":  "neonodes.renderers.tree.TreeRenderer",
    "array": "neonodes.renderers.array.ArrayRenderer",
    "graph": "neonodes.renderers.graph.GraphRenderer",
    "dp":    "neonodes.renderers.dp.DPRenderer",
}

# Map problem id → module path for dynamic loading
PROBLEM_MAP = {
    "count_islands":      "neonodes.problems.count_islands",
    "bt_inorder":         "neonodes.problems.bt_inorder",
    "bt_preorder":        "neonodes.problems.bt_preorder",
    "bt_postorder":       "neonodes.problems.bt_postorder",
    "bt_max_depth":       "neonodes.problems.bt_max_depth",
    "bt_path_sum":        "neonodes.problems.bt_path_sum",
    "bt_level_order":     "neonodes.problems.bt_level_order",
    "balanced_bt":        "neonodes.problems.balanced_bt",
    "diameter_bt":        "neonodes.problems.diameter_bt",
    "flatten_tree":       "neonodes.problems.flatten_tree",
    "invert_tree":        "neonodes.problems.invert_tree",
    "kth_smallest_bst":   "neonodes.problems.kth_smallest_bst",
    "lca_bst":            "neonodes.problems.lca_bst",
    "lca_bt":             "neonodes.problems.lca_bt",
    "max_path_sum":       "neonodes.problems.max_path_sum",
    "path_sum_ii":        "neonodes.problems.path_sum_ii",
    "right_side_view":    "neonodes.problems.right_side_view",
    "sum_numbers":        "neonodes.problems.sum_numbers",
    "symmetric_tree":     "neonodes.problems.symmetric_tree",
    "validate_bst":       "neonodes.problems.validate_bst",
    "zigzag_level_order": "neonodes.problems.zigzag_level_order",
    "two_sum":            "neonodes.problems.two_sum",
    "merge_intervals":    "neonodes.problems.merge_intervals",
    "valid_parens":       "neonodes.problems.valid_parens",
    "dijkstra":           "neonodes.problems.dijkstra",
    "bfs_graph":          "neonodes.problems.bfs_graph",
    "lcs":                "neonodes.problems.lcs",
}
