TOPICS = ["all", "grid", "tree", "graph", "array", "string", "dp", "sliding_window", "two_pointer", "stack", "queue", "linked_list"]
DIFFICULTIES = ["all", "easy", "medium", "hard"]

PROBLEMS = [
    {"id": "count_islands",      "title": "Count Islands",                  "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "number_of_islands",  "title": "Number of Islands II",           "topic": "grid",   "difficulty": "hard",   "renderer": "grid",  "available": True},
    {"id": "bt_inorder",         "title": "Binary Tree Inorder Traversal",  "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_preorder",        "title": "Binary Tree Preorder Traversal", "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_postorder",       "title": "Binary Tree Postorder Traversal", "topic": "tree",  "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_max_depth",       "title": "Maximum Depth of Binary Tree",   "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_path_sum",        "title": "Binary Tree Path Sum",           "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_level_order",     "title": "Binary Tree Level Order BFS",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "balanced_bt",        "title": "Balanced Binary Tree",           "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "diameter_bt",        "title": "Diameter of Binary Tree",        "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "flatten_tree",       "title": "Flatten Binary Tree to List",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "invert_tree",        "title": "Invert Binary Tree",             "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "kth_smallest_bst",   "title": "Kth Smallest Element in BST",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "lca_bst",            "title": "Lowest Common Ancestor of BST",  "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "lca_bt",             "title": "Lowest Common Ancestor of BT",   "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "max_path_sum",       "title": "Binary Tree Max Path Sum",       "topic": "tree",   "difficulty": "hard",   "renderer": "tree",  "available": True},
    {"id": "path_sum_ii",        "title": "Binary Tree Path Sum II",        "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "right_side_view",    "title": "Binary Tree Right Side View",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "sum_numbers",        "title": "Sum Root to Leaf Numbers",       "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "symmetric_tree",     "title": "Symmetric Tree",                 "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "validate_bst",       "title": "Validate Binary Search Tree",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "zigzag_level_order", "title": "BT Zigzag Level Order BFS",      "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "two_sum",            "title": "Two Sum",                        "topic": "array",  "difficulty": "easy",   "renderer": "array", "available": True},
    {"id": "merge_intervals",    "title": "Merge Intervals",                "topic": "array",  "difficulty": "medium", "renderer": "array", "available": True},
    {"id": "valid_parens",       "title": "Valid Parentheses",              "topic": "string", "difficulty": "easy",   "renderer": "array", "available": True},
    {"id": "dijkstra",           "title": "Dijkstra Shortest Path",         "topic": "graph",  "difficulty": "medium", "renderer": "graph", "available": True},
    {"id": "bfs_graph",          "title": "Graph BFS",                      "topic": "graph",  "difficulty": "easy",   "renderer": "graph", "available": True},
    {"id": "lcs",                "title": "Longest Common Subsequence",     "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},

    # --- Sliding Window (10) ---
    {"id": "longest_substring_no_repeat", "title": "Longest Substring No Repeat", "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "min_size_subarray_sum",      "title": "Minimum Size Subarray Sum",     "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "max_consecutive_ones_iii",    "title": "Max Consecutive Ones III",     "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "permutation_in_string",       "title": "Permutation in String",        "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "find_all_anagrams",           "title": "Find All Anagrams in String",  "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "min_window_substring",        "title": "Minimum Window Substring",     "topic": "sliding_window", "difficulty": "hard",   "renderer": "sliding_window", "available": True},
    {"id": "longest_repeating_char_replace", "title": "Longest Repeating Char Replace", "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "sliding_window_maximum",      "title": "Sliding Window Maximum",       "topic": "sliding_window", "difficulty": "hard",   "renderer": "sliding_window", "available": True},
    {"id": "subarrays_k_different",       "title": "Subarrays with K Diff Ints",   "topic": "sliding_window", "difficulty": "hard",   "renderer": "sliding_window", "available": True},
    {"id": "fruit_into_baskets",          "title": "Fruit Into Baskets",           "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},

    # --- Two Pointer (10) ---
    {"id": "valid_palindrome",           "title": "Valid Palindrome",              "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "two_sum_sorted",             "title": "Two Sum II - Sorted Array",     "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "three_sum",                  "title": "3Sum",                          "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "container_water",            "title": "Container With Most Water",     "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "trapping_rain_water",        "title": "Trapping Rain Water",           "topic": "two_pointer",    "difficulty": "hard",   "renderer": "two_pointer",    "available": True},
    {"id": "sort_colors",                "title": "Sort Colors (Three Pointer)",   "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "remove_duplicates",          "title": "Remove Duplicates from Sorted", "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "move_zeroes",                "title": "Move Zeroes",                   "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "backspace_compare",          "title": "Backspace String Compare",      "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "assign_cookies",             "title": "Assign Cookies",                "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},

    # --- Stack (10) ---
    {"id": "min_stack",                  "title": "Min Stack",                     "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "eval_rpn",                   "title": "Evaluate Reverse Polish Notation","topic": "stack",        "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "generate_parentheses",       "title": "Generate Parentheses",          "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "daily_temperatures",         "title": "Daily Temperatures",            "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "next_greater_element",       "title": "Next Greater Element I",        "topic": "stack",          "difficulty": "easy",   "renderer": "stack",          "available": True},
    {"id": "simplify_path",              "title": "Simplify Path",                 "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "asteroid_collision",         "title": "Asteroid Collision",            "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "online_stock_span",          "title": "Online Stock Span",             "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "basic_calculator",           "title": "Basic Calculator",              "topic": "stack",          "difficulty": "hard",   "renderer": "stack",          "available": True},
    {"id": "remove_k_digits",            "title": "Remove K Digits",               "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},

    # --- Queue (10) ---
    {"id": "implement_stack_queue",      "title": "Implement Stack using Queues",   "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "implement_queue_stack",      "title": "Implement Queue using Stacks",   "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "recent_calls",               "title": "Number of Recent Calls",        "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "first_unique_char",          "title": "First Unique Char in String",   "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "moving_average",             "title": "Moving Average from Stream",    "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "circular_queue",             "title": "Design Circular Queue",         "topic": "queue",          "difficulty": "medium", "renderer": "queue",          "available": True},
    {"id": "task_scheduler",             "title": "Task Scheduler",                "topic": "queue",          "difficulty": "medium", "renderer": "queue",          "available": True},
    {"id": "max_sliding_window_queue",   "title": "Sliding Window Max (Deque)",    "topic": "queue",          "difficulty": "hard",   "renderer": "queue",          "available": True},
    {"id": "walls_and_gates",            "title": "Walls and Gates (BFS)",         "topic": "queue",          "difficulty": "medium", "renderer": "queue",          "available": True},
    {"id": "rotting_oranges",            "title": "Rotting Oranges (BFS)",         "topic": "queue",          "difficulty": "medium", "renderer": "queue",          "available": True},

    # --- Linked List (10) ---
    {"id": "reverse_linked_list",        "title": "Reverse Linked List",           "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "merge_two_lists",            "title": "Merge Two Sorted Lists",        "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "linked_list_cycle",          "title": "Linked List Cycle",             "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "remove_nth_from_end",        "title": "Remove Nth Node From End",      "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "reorder_list",               "title": "Reorder List",                  "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "copy_random_list",           "title": "Copy List with Random Pointer", "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "add_two_numbers",            "title": "Add Two Numbers",               "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "intersection_two_lists",     "title": "Intersection of Two Lists",     "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "palindrome_linked_list",     "title": "Palindrome Linked List",        "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "odd_even_list",              "title": "Odd Even Linked List",          "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
]

RENDERER_MAP = {
    "grid":           "neonodes.renderers.grid.GridRenderer",
    "tree":           "neonodes.renderers.tree.TreeRenderer",
    "array":          "neonodes.renderers.array.ArrayRenderer",
    "graph":          "neonodes.renderers.graph.GraphRenderer",
    "dp":             "neonodes.renderers.dp.DPRenderer",
    "sliding_window": "neonodes.renderers.sliding_window.SlidingWindowRenderer",
    "two_pointer":    "neonodes.renderers.two_pointer.TwoPointerRenderer",
    "stack":          "neonodes.renderers.stack.StackRenderer",
    "queue":          "neonodes.renderers.queue.QueueRenderer",
    "linked_list":    "neonodes.renderers.linked_list.LinkedListRenderer",
}

PROBLEM_MAP = {
    "count_islands":      "neonodes.problems.count_islands",
    "number_of_islands":  "neonodes.problems.number_of_islands",
    "bt_inorder":         "neonodes.problems.bt_inorder",
    "bt_preorder":        "neonodes.problems.bt_preorder",
    "bt_postorder":       "neonodes.problems.bt_postorder",
    "bt_max_depth":       "neonodes.problems.bt_max_depth",
    "bt_path_sum":        "neonodes.problems.bt_path_sum",
    "bt_level_order":     "neonodes.problems.bt_level_order",
    "balanced_bt":        "neonodes.problems.balanced_bt",
    "diameter_bt":        "neonodes.problems.diameter_bt",
    "flatten_tree":       "neonodes.problems.flatten_tree",
    "invert_tree":        "neonodes.problems.invert_tree",
    "kth_smallest_bst":   "neonodes.problems.kth_smallest_bst",
    "lca_bst":            "neonodes.problems.lca_bst",
    "lca_bt":             "neonodes.problems.lca_bt",
    "max_path_sum":       "neonodes.problems.max_path_sum",
    "path_sum_ii":        "neonodes.problems.path_sum_ii",
    "right_side_view":    "neonodes.problems.right_side_view",
    "sum_numbers":        "neonodes.problems.sum_numbers",
    "symmetric_tree":     "neonodes.problems.symmetric_tree",
    "validate_bst":       "neonodes.problems.validate_bst",
    "zigzag_level_order": "neonodes.problems.zigzag_level_order",
    "two_sum":            "neonodes.problems.two_sum",
    "merge_intervals":    "neonodes.problems.merge_intervals",
    "valid_parens":       "neonodes.problems.valid_parens",
    "dijkstra":           "neonodes.problems.dijkstra",
    "bfs_graph":          "neonodes.problems.bfs_graph",
    "lcs":                "neonodes.problems.lcs",

    # --- Sliding Window ---
    "longest_substring_no_repeat": "neonodes.problems.longest_substring_no_repeat",
    "min_size_subarray_sum":      "neonodes.problems.min_size_subarray_sum",
    "max_consecutive_ones_iii":    "neonodes.problems.max_consecutive_ones_iii",
    "permutation_in_string":       "neonodes.problems.permutation_in_string",
    "find_all_anagrams":           "neonodes.problems.find_all_anagrams",
    "min_window_substring":        "neonodes.problems.min_window_substring",
    "longest_repeating_char_replace": "neonodes.problems.longest_repeating_char_replace",
    "sliding_window_maximum":      "neonodes.problems.sliding_window_maximum",
    "subarrays_k_different":       "neonodes.problems.subarrays_k_different",
    "fruit_into_baskets":          "neonodes.problems.fruit_into_baskets",

    # --- Two Pointer ---
    "valid_palindrome":           "neonodes.problems.valid_palindrome",
    "two_sum_sorted":             "neonodes.problems.two_sum_sorted",
    "three_sum":                  "neonodes.problems.three_sum",
    "container_water":            "neonodes.problems.container_water",
    "trapping_rain_water":        "neonodes.problems.trapping_rain_water",
    "sort_colors":                "neonodes.problems.sort_colors",
    "remove_duplicates":          "neonodes.problems.remove_duplicates",
    "move_zeroes":                "neonodes.problems.move_zeroes",
    "backspace_compare":          "neonodes.problems.backspace_compare",
    "assign_cookies":             "neonodes.problems.assign_cookies",

    # --- Stack ---
    "min_stack":                  "neonodes.problems.min_stack",
    "eval_rpn":                   "neonodes.problems.eval_rpn",
    "generate_parentheses":       "neonodes.problems.generate_parentheses",
    "daily_temperatures":         "neonodes.problems.daily_temperatures",
    "next_greater_element":       "neonodes.problems.next_greater_element",
    "simplify_path":              "neonodes.problems.simplify_path",
    "asteroid_collision":         "neonodes.problems.asteroid_collision",
    "online_stock_span":          "neonodes.problems.online_stock_span",
    "basic_calculator":           "neonodes.problems.basic_calculator",
    "remove_k_digits":            "neonodes.problems.remove_k_digits",

    # --- Queue ---
    "implement_stack_queue":      "neonodes.problems.implement_stack_queue",
    "implement_queue_stack":      "neonodes.problems.implement_queue_stack",
    "recent_calls":               "neonodes.problems.recent_calls",
    "first_unique_char":          "neonodes.problems.first_unique_char",
    "moving_average":             "neonodes.problems.moving_average",
    "circular_queue":             "neonodes.problems.circular_queue",
    "task_scheduler":             "neonodes.problems.task_scheduler",
    "max_sliding_window_queue":   "neonodes.problems.max_sliding_window_queue",
    "walls_and_gates":            "neonodes.problems.walls_and_gates",
    "rotting_oranges":            "neonodes.problems.rotting_oranges",

    # --- Linked List ---
    "reverse_linked_list":        "neonodes.problems.reverse_linked_list",
    "merge_two_lists":            "neonodes.problems.merge_two_lists",
    "linked_list_cycle":          "neonodes.problems.linked_list_cycle",
    "remove_nth_from_end":        "neonodes.problems.remove_nth_from_end",
    "reorder_list":               "neonodes.problems.reorder_list",
    "copy_random_list":           "neonodes.problems.copy_random_list",
    "add_two_numbers":            "neonodes.problems.add_two_numbers",
    "intersection_two_lists":     "neonodes.problems.intersection_two_lists",
    "palindrome_linked_list":     "neonodes.problems.palindrome_linked_list",
    "odd_even_list":              "neonodes.problems.odd_even_list",
}
